### ISSUE TITLE
Implement Upload

### ISSUE THREAD

**Issue by mwinche** [Workfront/workfront-api#10]
@bhovhannes I love what you've done so far. I find that I need to make use of the upload feature to attach some documents to some issues for my script.

I'm assuming that you're okay with it as you have a stub out there. How would you recommend I proceed? Or should I just start working on a PR?

**Comment by bhovhannes** [comment]
@mwinche, document upload feature was also mentioned multiple times in stackoverflow and certainly is a feature the customers will love. I was also thinking about implementing it, just didn't managed to find a time to do that. If you'll have time to work on implementation, I'd like to accept your PR :)

I've some thoughts regarding how it should be implemented:
1. A new file named `upload.js` should be added to `src/plugins/` folder. It will contain method for uploading file and getting its handle.
2. Document new method with JsDoc. JsDoc comment will be used to generate API docs afterwards.
3. The file `upload.js` should be excluded from browser bundle, because upload can't work in browser-based environments. In order to exclude it, tweak `build` task in gulpfile.js.
4. Make sure to add an example in `examples/node/` folder illustrating usage of new method.
5. I was thinking about using [form-data](https://www.npmjs.com/package/form-data) package, but if you have a better choice, feel free to use it.

**Comment by mwinche** [comment]
Thanks @bhovhannes! I'll start working on it now!
